Auto Balance code integrated into smokey
Team4682CyBears/ChargedUp2023 pull request #38
Opened 2023-01-25 18:03 UTC by josieammer

Tested in lab on veer chassis.  Successfully balances ramp in a variety of stating conditions.

2023-02-15 01:08 UTC, mmcadamsms requested changes
Ok ... I've left comments in the PR take a look and decide how you'd like to proceed.

2023-02-15 01:08 UTC, mmcadamsms commented on smokey/src/main/java/frc/robot/commands/AutoBalanceStepCommand.java
> +    //Translation2d angleOfSteepestAscent = QuaternionUtils.getAngleOfSteepestAscent(navxsubsystem.getQuaterion());
remove the commented out stuff ... I presume we don't need it?

2023-02-15 01:08 UTC, mmcadamsms commented on smokey/src/main/java/frc/robot/commands/AutoBalanceStepCommand.java
> +    drivetrainsubsystem.drive(new ChassisSpeeds(xVelocity, yVelocity, rotVelocity));
I think we should avoid calling drive twice in the case when it is elapsed.

2023-02-15 14:32 UTC, josieammer commented on camp/abolotski/UltrasonicSensorTest/src/main/java/frc/robot/commands/GetUltrasonic.java
> +
Not yet.  We could pull it out to a mini project until we need it in Smokey.

2023-02-15 14:44 UTC, josieammer commented on smokey/src/main/java/frc/robot/subsystems/NavxSubsystem.java
> +    if(swerveNavx.isCalibrating()){
I think a high-level retry would be a good idea as long as we can guarantee the robot won't move during the wait time.

2023-02-15 14:48 UTC, josieammer commented on smokey/src/main/java/frc/robot/swerveHelpers/Falcon500SteerControllerFactoryBuilder.java
>                  if (++resetIteration >= ENCODER_RESET_ITERATIONS) {
If the robot is enabled before this happens the first time, the robot is disoriented.  
Is there a way to ensure this happens without delay at construction?
If not, should we set a flag on the first time through, and then print the message once to alert the user it's OK to enable.

2023-02-15 23:41 UTC, asherbolotski commented on camp/abolotski/UltrasonicSensorTest/src/main/java/frc/robot/commands/GetUltrasonic.java
> +
This file is in the camp folder so it doesn't affect smokey

2023-02-15 23:43 UTC, asherbolotski commented on smokey/src/main/java/frc/robot/Constants.java
> +import java.lang.Math;
no, deleted

2023-02-16 02:45 UTC, mmcadamsms approved these changes
ok ... lets do this

2023-02-16 02:45 UTC, mmcadamsms approved these changes
ok ... lets do this

2023-02-16 02:45 UTC, merged